### ISSUE TITLE
Need help to find the package 

### ISSUE THREAD

**Issue by 4ff4n** [jgomezgadea/accurate_docking#1]
Hello.
I am trying to use **accurate_docking** for my DIY project and having some trouble integrating the code. it seems like i am missing robotnik_navigation_msgs package but i am unable to find this package anywhere on https://github.com/RobotnikAutomation.

from tf import TransformListener 
from tf.transformations import euler_from_quaternion
from **robotnik_navigation_msgs**.msg import **MoveAction, MoveActionGoa**
from **robotnik_navigation_msgs**.msg import **DockAction**

where can i find robotnik_navigation_msgs package and the respective messages definitions being imported from this package?

**Comment by jgomezgadea** [comment]
Hello,

This package is developed to be used with the Robotnik robots, that already have that package installed. I am going to attach the .deb file with the robotnik_navigation_msgs, but I am not sure if you will be able to compile and execute this package even with this dependency.

If it works, I recommend to use the updated version of this package, on https://github.com/RobotnikAutomation/accurate_docking.

[robotnik_navigation_msgs_deb.zip](https://github.com/jgomezRobotnik/accurate_docking/files/5161004/robotnik_navigation_msgs_deb.zip)

**Comment by loukas9704** [comment]
Does this package robotnik_navigation_msgs_deb comes in i386 version for 32bit xenials?

**Comment by jgomezgadea** [comment]
The [robotnik_navigation_msgs](https://github.com/RobotnikAutomation/robotnik_navigation_msgs.git) has been moved to a public repository, so you can clone the package inside your catkin workspace without installing the .deb.

**Comment by loukas9704** [comment]
i have a problem with launch detector_and_docker.launch 
where i can find this file?
![image](https://user-images.githubusercontent.com/72103348/108389504-68534000-7218-11eb-88f2-68d29d7d263f.png)

**Comment by kgeorg22** [comment]
Hello, i have the same issue as @loukas9704
